// stores/food.js
import { defineStore } from "pinia";
import { ref } from "vue"; // Import ref from 'vue', not 'pinia'

export const useFoodStore = defineStore(
  "food",
  () => {
    // Base de alimentos
    const foodDatabase = [
      {
        id: 1,
        label: "Apple (medium, ~182 g, com casca)",
        unit: "piece",
        calories: 95,
        protein: 0.5,
        carbs: 25,
        defaultQuantity: 1,
      },
      {
        id: 2,
        label: "Banana (medium, ~118 g)",
        unit: "piece",
        calories: 105,
        protein: 1.3,
        carbs: 27,
        defaultQuantity: 1,
      },
      {
        id: 3,
        label: "Chicken Breast (cooked, skinless)",
        unit: "g",
        calories: 248, // 165 kcal/100g → 247.5 por 150g
        protein: 46.5, // 31 g/100g → 46.5 g por 150g
        carbs: 0,
        defaultQuantity: 150, // 150 g
      },
      {
        id: 4,
        label: "Brown Rice (cooked)",
        unit: "cup",
        calories: 218, // 1 cup cozido (~195 g)
        protein: 4.5,
        carbs: 45.8,
        defaultQuantity: 1,
      },
      {
        id: 5,
        label: "Broccoli (chopped, raw)",
        unit: "cup",
        calories: 31,
        protein: 2.5,
        carbs: 6,
        defaultQuantity: 1,
      },
      {
        id: 6,
        label: "Salmon (cooked)",
        unit: "g",
        calories: 208, // por 100 g
        protein: 20,
        carbs: 0,
        defaultQuantity: 100,
      },
      {
        id: 7,
        label: "Egg (large, whole)",
        unit: "piece",
        calories: 78,
        protein: 6.3,
        carbs: 0.6,
        defaultQuantity: 1,
      },
      {
        id: 8,
        label: "Almonds (dry roasted, unsalted)",
        unit: "oz",
        calories: 164, // 1 oz (28 g)
        protein: 6,
        carbs: 6,
        defaultQuantity: 1,
      },
      {
        id: 9,
        label: "Plain Yogurt (whole milk)",
        unit: "cup",
        calories: 149, // 1 cup (~245 g)
        protein: 8.5,
        carbs: 11.4,
        defaultQuantity: 1,
      },
      {
        id: 10,
        label: "Oatmeal (cooked in water, rolled oats)",
        unit: "cup",
        calories: 166, // 1 cup cozido
        protein: 6,
        carbs: 28.1,
        defaultQuantity: 1,
      },
      {
        id: 11,
        label: "Avocado (medium, edible portion)",
        unit: "piece",
        calories: 240, // médio inteiro (~240 kcal)
        protein: 3,
        carbs: 12,
        defaultQuantity: 1,
      },
      {
        id: 12,
        label: "Sweet Potato (medium, baked without skin)",
        unit: "piece",
        calories: 112, // médio ~130 g, sem casca
        protein: 2,
        carbs: 26,
        defaultQuantity: 1,
      },
      {
        id: 13,
        label: "Spinach (raw)",
        unit: "cup",
        calories: 7,
        protein: 0.9,
        carbs: 1.1,
        defaultQuantity: 1,
      },
      {
        id: 14,
        label: "Whole Wheat Bread",
        unit: "piece",
        calories: 69, // por fatia (~28 g). Duas fatias ≈ 138 kcal
        protein: 3.6,
        carbs: 12,
        defaultQuantity: 2, // 2 fatias = 138 kcal aprox.
      },
      {
        id: 15,
        label: "Peanut Butter (smooth, unsalted)",
        unit: "serving", // 2 tbsp (32 g)
        calories: 188,
        protein: 8,
        carbs: 6.3,
        defaultQuantity: 1,
      },
      {
        id: 16,
        label: "Beer (regular, 12 fl oz, ~355 g)",
        unit: "fl oz",
        calories: 146,
        protein: 1.0,
        carbs: 13.0,
        defaultQuantity: 1,
      },
      {
        id: 17,
        label: "Wine (table red, 3.5 fl oz, ~103 g)",
        unit: "fl oz",
        calories: 74,
        protein: 0.0,
        carbs: 2.0,
        defaultQuantity: 1,
      },
      {
        id: 18,
        label: "Cola (12 fl oz, ~370 g)",
        unit: "fl oz",
        calories: 152,
        protein: 0.0,
        carbs: 38.0,
        defaultQuantity: 1,
      },
      {
        id: 19,
        label: "Coffee (brewed, 6 fl oz, ~178 g)",
        unit: "fl oz",
        calories: 4,
        protein: 0.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 20,
        label: "Cranberry juice cocktail (8 fl oz, ~253 g)",
        unit: "fl oz",
        calories: 144,
        protein: 0.0,
        carbs: 36.0,
        defaultQuantity: 1,
      },
      {
        id: 21,
        label: "Lemonade (frozen concentrate prepared, 8 fl oz, ~248 g)",
        unit: "fl oz",
        calories: 99,
        protein: 0.0,
        carbs: 26.0,
        defaultQuantity: 1,
      },
      {
        id: 22,
        label: "Tea (black brewed, 6 fl oz, ~178 g)",
        unit: "fl oz",
        calories: 2,
        protein: 0.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 23,
        label: "Blue cheese (1 oz, ~28 g)",
        unit: "oz",
        calories: 100,
        protein: 6.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 24,
        label: "Cheddar cheese (1 oz, ~28 g)",
        unit: "oz",
        calories: 114,
        protein: 7.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 25,
        label: "Cottage cheese (creamed large curd, 1 cup, ~225 g)",
        unit: "cup",
        calories: 233,
        protein: 28.0,
        carbs: 6.0,
        defaultQuantity: 1,
      },
      {
        id: 26,
        label: "Cream cheese (regular, 1 oz, ~28 g)",
        unit: "oz",
        calories: 99,
        protein: 2.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 27,
        label: "Feta cheese (1 oz, ~28 g)",
        unit: "oz",
        calories: 75,
        protein: 4.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 28,
        label: "Mozzarella cheese (whole milk, 1 oz, ~28 g)",
        unit: "oz",
        calories: 80,
        protein: 6.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 29,
        label: "Parmesan cheese (grated, 1 oz, ~28 g)",
        unit: "oz",
        calories: 129,
        protein: 12.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 30,
        label: "Swiss cheese (1 oz, ~28 g)",
        unit: "oz",
        calories: 107,
        protein: 8.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 31,
        label: "American cheese (regular, 1 oz, ~28 g)",
        unit: "oz",
        calories: 106,
        protein: 6.0,
        carbs: 2.0,
        defaultQuantity: 1,
      },
      {
        id: 32,
        label: "Half and half (1 cup, ~242 g)",
        unit: "cup",
        calories: 315,
        protein: 7.0,
        carbs: 10.0,
        defaultQuantity: 1,
      },
      {
        id: 33,
        label: "Sour cream (regular, 1 cup, ~230 g)",
        unit: "cup",
        calories: 493,
        protein: 7.0,
        carbs: 10.0,
        defaultQuantity: 1,
      },
      {
        id: 34,
        label: "Frozen yogurt (vanilla, 1/2 cup, ~72 g)",
        unit: "cup",
        calories: 114,
        protein: 3.0,
        carbs: 17.0,
        defaultQuantity: 1,
      },
      {
        id: 35,
        label: "Ice cream (vanilla, 1/2 cup, ~66 g)",
        unit: "cup",
        calories: 133,
        protein: 2.0,
        carbs: 16.0,
        defaultQuantity: 1,
      },
      {
        id: 36,
        label: "Milk (whole, 1 cup, ~244 g)",
        unit: "cup",
        calories: 150,
        protein: 8.0,
        carbs: 12.0,
        defaultQuantity: 1,
      },
      {
        id: 37,
        label: "Milk (nonfat, 1 cup, ~245 g)",
        unit: "cup",
        calories: 86,
        protein: 8.0,
        carbs: 12.0,
        defaultQuantity: 1,
      },
      {
        id: 38,
        label: "Buttermilk (1 cup, ~245 g)",
        unit: "cup",
        calories: 99,
        protein: 8.0,
        carbs: 12.0,
        defaultQuantity: 1,
      },
      {
        id: 39,
        label: "Evaporated milk (whole, 1 cup, ~252 g)",
        unit: "cup",
        calories: 339,
        protein: 17.0,
        carbs: 25.0,
        defaultQuantity: 1,
      },
      {
        id: 40,
        label: "Nonfat dry milk (instant, 1 cup, ~68 g)",
        unit: "cup",
        calories: 244,
        protein: 24.0,
        carbs: 35.0,
        defaultQuantity: 1,
      },
      {
        id: 41,
        label: "Chocolate milk (whole, 1 cup, ~250 g)",
        unit: "cup",
        calories: 208,
        protein: 8.0,
        carbs: 26.0,
        defaultQuantity: 1,
      },
      {
        id: 42,
        label: "Eggnog (1 cup, ~254 g)",
        unit: "cup",
        calories: 342,
        protein: 10.0,
        carbs: 34.0,
        defaultQuantity: 1,
      },
      {
        id: 43,
        label: "Butter (salted, 1 tbsp, ~14 g)",
        unit: "tbsp",
        calories: 102,
        protein: 0.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 44,
        label: "Margarine (regular, 1 tbsp, ~14 g)",
        unit: "tbsp",
        calories: 101,
        protein: 0.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 45,
        label: "Canola oil (1 tbsp, ~14 g)",
        unit: "tbsp",
        calories: 124,
        protein: 0.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 46,
        label: "Olive oil (1 tbsp, ~14 g)",
        unit: "tbsp",
        calories: 119,
        protein: 0.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 47,
        label: "Peanut oil (1 tbsp, ~14 g)",
        unit: "tbsp",
        calories: 119,
        protein: 0.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 48,
        label: "Blue cheese dressing (regular, 1 tbsp, ~15 g)",
        unit: "tbsp",
        calories: 77,
        protein: 1.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 49,
        label: "French dressing (regular, 1 tbsp, ~16 g)",
        unit: "tbsp",
        calories: 67,
        protein: 0.0,
        carbs: 3.0,
        defaultQuantity: 1,
      },
      {
        id: 50,
        label: "Italian dressing (regular, 1 tbsp, ~15 g)",
        unit: "tbsp",
        calories: 69,
        protein: 0.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 51,
        label: "Mayonnaise (regular, 1 tbsp, ~14 g)",
        unit: "tbsp",
        calories: 99,
        protein: 0.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 52,
        label: "Catfish (breaded fried, 3 oz, ~85 g)",
        unit: "oz",
        calories: 195,
        protein: 15.0,
        carbs: 7.0,
        defaultQuantity: 1,
      },
      {
        id: 53,
        label: "Clam (raw meat, 3 oz, ~85 g)",
        unit: "oz",
        calories: 63,
        protein: 11.0,
        carbs: 2.0,
        defaultQuantity: 1,
      },
      {
        id: 54,
        label: "Cod (baked, 3 oz, ~85 g)",
        unit: "oz",
        calories: 89,
        protein: 20.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 55,
        label: "Crab (Alaska king steamed, 3 oz, ~85 g)",
        unit: "oz",
        calories: 82,
        protein: 16.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 56,
        label: "Flounder (baked, 3 oz, ~85 g)",
        unit: "oz",
        calories: 99,
        protein: 21.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 57,
        label: "Haddock (baked, 3 oz, ~85 g)",
        unit: "oz",
        calories: 95,
        protein: 21.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 58,
        label: "Halibut (baked, 3 oz, ~85 g)",
        unit: "oz",
        calories: 119,
        protein: 23.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 59,
        label: "Herring (pickled, 3 oz, ~85 g)",
        unit: "oz",
        calories: 223,
        protein: 12.0,
        carbs: 8.0,
        defaultQuantity: 1,
      },
      {
        id: 60,
        label: "Lobster (steamed, 3 oz, ~85 g)",
        unit: "oz",
        calories: 83,
        protein: 17.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 61,
        label: "Oyster (raw, 3 oz, ~84 g)",
        unit: "oz",
        calories: 57,
        protein: 6.0,
        carbs: 3.0,
        defaultQuantity: 1,
      },
      {
        id: 62,
        label: "Tuna (canned water pack chunk light, 3 oz, ~85 g)",
        unit: "oz",
        calories: 99,
        protein: 22.0,
        carbs: 0.0,
        defaultQuantity: 1,
      },
      {
        id: 63,
        label: "Apricot (raw, 1 piece, ~35 g)",
        unit: "piece",
        calories: 17,
        protein: 0.0,
        carbs: 4.0,
        defaultQuantity: 1,
      },
      {
        id: 64,
        label: "Blackberry (raw, 1 cup, ~144 g)",
        unit: "cup",
        calories: 75,
        protein: 1.0,
        carbs: 18.0,
        defaultQuantity: 1,
      },
      {
        id: 65,
        label: "Blueberry (raw, 1 cup, ~145 g)",
        unit: "cup",
        calories: 81,
        protein: 1.0,
        carbs: 20.0,
        defaultQuantity: 1,
      },
      {
        id: 66,
        label: "Cherry (sweet raw, 10 pieces, ~68 g)",
        unit: "piece",
        calories: 49,
        protein: 1.0,
        carbs: 11.0,
        defaultQuantity: 10,
      },
      {
        id: 67,
        label: "Cranberry (dried sweetened, 1/4 cup, ~28 g)",
        unit: "cup",
        calories: 92,
        protein: 0.0,
        carbs: 24.0,
        defaultQuantity: 0.25,
      },
      {
        id: 68,
        label: "Date (whole without pits, 5 pieces, ~42 g)",
        unit: "piece",
        calories: 116,
        protein: 1.0,
        carbs: 31.0,
        defaultQuantity: 5,
      },
      {
        id: 69,
        label: "Fig (dried, 2 pieces, ~38 g)",
        unit: "piece",
        calories: 97,
        protein: 1.0,
        carbs: 25.0,
        defaultQuantity: 2,
      },
      {
        id: 70,
        label: "Grapefruit (pink raw half, ~123 g)",
        unit: "piece",
        calories: 37,
        protein: 1.0,
        carbs: 9.0,
        defaultQuantity: 0.5,
      },
      {
        id: 71,
        label: "Grape (seedless raw, 1 cup, ~160 g)",
        unit: "cup",
        calories: 114,
        protein: 1.0,
        carbs: 28.0,
        defaultQuantity: 1,
      },
      {
        id: 72,
        label: "Kiwi fruit (raw medium, 1 piece, ~76 g)",
        unit: "piece",
        calories: 46,
        protein: 1.0,
        carbs: 11.0,
        defaultQuantity: 1,
      },
      {
        id: 73,
        label: "Mango (raw whole, 1 piece, ~207 g)",
        unit: "piece",
        calories: 135,
        protein: 1.0,
        carbs: 35.0,
        defaultQuantity: 1,
      },
      {
        id: 74,
        label: "Nectarine (raw, 1 piece, ~136 g)",
        unit: "piece",
        calories: 67,
        protein: 1.0,
        carbs: 16.0,
        defaultQuantity: 1,
      },
      {
        id: 75,
        label: "Rye bread (untoasted, 1 slice, ~32 g)",
        unit: "slice",
        calories: 83,
        protein: 3.0,
        carbs: 15.0,
        defaultQuantity: 1,
      },
      {
        id: 76,
        label: "White bread (untoasted, 1 slice, ~25 g)",
        unit: "slice",
        calories: 67,
        protein: 2.0,
        carbs: 12.0,
        defaultQuantity: 1,
      },
      {
        id: 77,
        label: "Dry bread crumbs (plain, enriched, 1 cup, ~108 g)",
        unit: "cup",
        calories: 427,
        protein: 14.0,
        carbs: 78.0,
        defaultQuantity: 1,
      },
      {
        id: 78,
        label: "Bread stuffing (prepared from dry mix, 1/2 cup, ~100 g)",
        unit: "cup",
        calories: 178,
        protein: 3.0,
        carbs: 22.0,
        defaultQuantity: 0.5,
      },
      {
        id: 79,
        label:
          "Corn grits (regular or quick, enriched, white, cooked, 1 cup, ~242 g)",
        unit: "cup",
        calories: 145,
        protein: 3.0,
        carbs: 31.0,
        defaultQuantity: 1,
      },
      {
        id: 80,
        label: "Cream of Wheat (regular, cooked, 1 cup, ~251 g)",
        unit: "cup",
        calories: 133,
        protein: 4.0,
        carbs: 28.0,
        defaultQuantity: 1,
      },
      {
        id: 81,
        label: "Malt-O-Meal (cooked, 1 cup, ~240 g)",
        unit: "cup",
        calories: 122,
        protein: 4.0,
        carbs: 26.0,
        defaultQuantity: 1,
      },
      {
        id: 82,
        label: "Wheatena (cooked, 1 cup, ~243 g)",
        unit: "cup",
        calories: 136,
        protein: 5.0,
        carbs: 29.0,
        defaultQuantity: 1,
      },
      {
        id: 83,
        label: "Cheerios (ready to eat, 1 cup, ~30 g)",
        unit: "cup",
        calories: 110,
        protein: 3.0,
        carbs: 23.0,
        defaultQuantity: 1,
      },
      {
        id: 84,
        label: "Corn Flakes (Kelloggs, ready to eat, 1 cup, ~28 g)",
        unit: "cup",
        calories: 102,
        protein: 2.0,
        carbs: 24.0,
        defaultQuantity: 1,
      },
      {
        id: 85,
        label: "Froot Loops (ready to eat, 1 cup, ~30 g)",
        unit: "cup",
        calories: 117,
        protein: 1.0,
        carbs: 26.0,
        defaultQuantity: 1,
      },
      {
        id: 86,
        label: "Frosted Flakes (ready to eat, 3/4 cup, ~31 g)",
        unit: "cup",
        calories: 119,
        protein: 1.0,
        carbs: 28.0,
        defaultQuantity: 0.75,
      },
      {
        id: 87,
        label: "Alfalfa sprouts (raw, 1 cup, ~33 g)",
        unit: "cup",
        calories: 10,
        protein: 1.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 88,
        label: "Artichokes (globe or French, cooked, drained, 1 cup, ~168 g)",
        unit: "cup",
        calories: 84,
        protein: 6.0,
        carbs: 19.0,
        defaultQuantity: 1,
      },
      {
        id: 89,
        label: "Asparagus (green, cooked from raw, 1 cup, ~180 g)",
        unit: "cup",
        calories: 43,
        protein: 5.0,
        carbs: 8.0,
        defaultQuantity: 1,
      },
      {
        id: 90,
        label: "Bamboo shoots (canned, drained, 1 cup, ~131 g)",
        unit: "cup",
        calories: 25,
        protein: 2.0,
        carbs: 4.0,
        defaultQuantity: 1,
      },
      {
        id: 91,
        label:
          "Lima beans (immature seeds, frozen, cooked, drained, Ford hooks, 1 cup, ~170 g)",
        unit: "cup",
        calories: 170,
        protein: 10.0,
        carbs: 32.0,
        defaultQuantity: 1,
      },
      {
        id: 92,
        label: "Snap beans (green, cooked from raw, 1 cup, ~125 g)",
        unit: "cup",
        calories: 44,
        protein: 2.0,
        carbs: 10.0,
        defaultQuantity: 1,
      },
      {
        id: 93,
        label: "Bean sprouts (mung, raw, 1 cup, ~104 g)",
        unit: "cup",
        calories: 31,
        protein: 3.0,
        carbs: 6.0,
        defaultQuantity: 1,
      },
      {
        id: 94,
        label: "Beets (cooked, drained, slices, 1 cup, ~170 g)",
        unit: "cup",
        calories: 75,
        protein: 3.0,
        carbs: 17.0,
        defaultQuantity: 1,
      },
      {
        id: 95,
        label: "Brussels sprouts (cooked from raw, 1 cup, ~156 g)",
        unit: "cup",
        calories: 61,
        protein: 4.0,
        carbs: 14.0,
        defaultQuantity: 1,
      },
      {
        id: 96,
        label: "Cabbage (common varieties, raw, shredded, 1 cup, ~70 g)",
        unit: "cup",
        calories: 18,
        protein: 1.0,
        carbs: 4.0,
        defaultQuantity: 1,
      },
      {
        id: 97,
        label: "Carrots (raw, whole, 7 1/2 long, 1 carrot, ~72 g)",
        unit: "piece",
        calories: 31,
        protein: 1.0,
        carbs: 7.0,
        defaultQuantity: 1,
      },
      {
        id: 98,
        label: "Cauliflower (raw, 1 cup, ~100 g)",
        unit: "cup",
        calories: 25,
        protein: 2.0,
        carbs: 5.0,
        defaultQuantity: 1,
      },
      {
        id: 99,
        label: "Celery (raw, stalk, 7 1/2 to 8 long, 1 stalk, ~40 g)",
        unit: "piece",
        calories: 6,
        protein: 0.0,
        carbs: 1.0,
        defaultQuantity: 1,
      },
      {
        id: 100,
        label: "Collards (cooked from raw, 1 cup, ~190 g)",
        unit: "cup",
        calories: 49,
        protein: 4.0,
        carbs: 9.0,
        defaultQuantity: 1,
      },
    ];

    // Logs persistidos com ref para reatividade
    const logs = ref([]);

    // Função para filtrar logs por data
    function logsForDate(dateIso) {
      return logs.value
        .filter((l) => l.date === dateIso)
        .map((log) => {
          const food = foodDatabase.find((f) => f.id === log.foodId) || {};
          return {
            id: log.id,
            date: log.date,
            label: food.label || "",
            quantity: log.quantity,
            unit: food.unit || "",
            calories: (food.calories || 0) * log.quantity,
            protein: (food.protein || 0) * log.quantity,
            carbs: (food.carbs || 0) * log.quantity,
          };
        });
    }

    // Ações com reatividade
    function addLog(log) {
      logs.value = [...logs.value, { ...log, id: Date.now() }];
    }

    function updateLog(id, data) {
      const idx = logs.value.findIndex((l) => l.id === id);
      if (idx > -1) {
        logs.value = logs.value.map((l, i) =>
          i === idx ? { ...l, ...data } : l
        );
      }
    }

    function deleteLog(id) {
      logs.value = logs.value.filter((l) => l.id !== id);
    }

    function clearAll() {
      logs.value = [];
    }

    return {
      foodDatabase,
      logs,
      logsForDate,
      addLog,
      updateLog,
      deleteLog,
      clearAll,
    };
  },
  {
    persist: process.client
      ? {
          storage: localStorage,
        }
      : false,
  }
);
